#!/bin/bash

declare -a cydia
cydia=($CYDIA)

launchctl unload "/Library/LaunchDaemons/com.darwindev.kbsynctool.plist" > /dev/null 2>&1
launchctl remove com.darwindev.kbsynctool > /dev/null 2>&1

killall -9 AppStore itunesstored appstored > /dev/null 2>&1

sleep 1
timeout -k 2 5 launchctl load -w -F "/Library/LaunchDaemons/com.darwindev.kbsynctool.plist" > /dev/null 2>&1

if [[ ${CYDIA+@} ]]; then
    eval "echo 'finish:restart' >&${cydia[0]}"
fi

exit 0
